#!/bin/bash -ex

# Quick test script to create a file.
# Epxected args:
#   1. WORKSPACE: path to the root of the the source.

WORKSPACE=$1
shift 1

cd $WORKSPACE
rm -rf $WORKSPACE/testdir
mkdir $WORKSPACE/tester

touch testfile.log
